controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
    path: /login
    controller: App\Controller\UserController::login

error_access_denied:
    path: /security/error_access_denied
    controller: App\Controller\ErrorController::accessDenied